name: uids_io_sdk_flutter
description: >
  A reusable Flutter authentication SDK supporting Google, Microsoft, and
  backend token exchange, session management, and device registration.
version: 0.2.0
homepage: https://github.com/uids-io/sdk_flutter.git
repository: https://github.com/uids-io/sdk_flutter.git

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^10.0.0
  http: ^1.2.0
  google_sign_in: ^7.2.0
  url_launcher: ^6.3.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  # This is a pure-Dart SDK — no assets or fonts.